server.port=9200
#
#####################################
# DB CONFIGS
#####################################
spring.datasource.url=jdbc:h2:./JCLDB
spring.datasource.username=sa
spring.datasource.password=
#
#####################################
# CACHING
#####################################
#spring.cache.cache-names=
#spring.cache.caffeine.spec=initialCapacity=50,maximumSize=10,expireAfterAccess=3600s
#
#####################################
# LOGGING
#####################################

